{% set name = "scikit-lego" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/koaning/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 182b32501a30dcf0c4a2995d6b6ccb597ed5b7203cb0fab2be60d185c65b42a4


build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - autograd >=1.2
    - deprecated >=1.2.6
    - pandas >=1.1.5
    - patsy >=0.5.1
    - python >=3.6
    - scikit-learn >=0.24.1
    - umap-learn >=0.4.6

test:
  imports:
    - sklego

about:
  home: https://github.com/koaning/scikit-lego
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: missing blocks for sklearn pipelines
  doc_url: https://scikit-lego.readthedocs.io

extra:
  recipe-maintainers:
    - maxibor
    - MBrouns
    - koaning
