{% set name = "scikit-lego" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/koaning/{{ name }}/archive/{{ version }}.tar.gz
  sha256: beab2ee732f20cdcef6fe9d58bad7fa3f197e57958f567eeebab21db0afa6082

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - numpy >=1.16.0
    - scipy >=1.2.0
    - scikit-learn >=0.20.2
    - pandas >=0.23.4
    - patsy >=0.5.1
    - autograd >=1.2
    - cvxpy >=1.0.24
    - Deprecated >=1.2.6
    - umap-learn >=0.4.3

test:
  imports:
    - sklego

about:
  home: https://github.com/koaning/scikit-lego
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: missing blocks for sklearn pipelines
  doc_url: https://scikit-lego.readthedocs.io

extra:
  recipe-maintainers:
    - maxibor
    - MBrouns
    - koaning
