{% set name = "scikit-lego" %}
{% set version = "0.6.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/koaning/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e3e8629c620b0cb472874bbae529997813fa4ca1446eec7ea8d15e47014a3291

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - autograd >=1.2
    - deprecated >=1.2.6
    - pandas >=1.1.5
    - patsy >=0.5.1
    - python >=3.6
    - scikit-learn >=0.24.1
    - umap-learn >=0.4.6

test:
  imports:
    - sklego

about:
  home: https://github.com/koaning/scikit-lego
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: missing blocks for sklearn pipelines
  doc_url: https://scikit-lego.readthedocs.io

extra:
  recipe-maintainers:
    - maxibor
    - MBrouns
    - koaning
